export const countries = [
  {
    id: "IND",
    id2: "IN",
    display: "Bharat/India",
    value: "Republic of Bharat/India",
  },
  {
    id: "AFG",
    id2: "AF",
    display: "Afghanistan",
    value: "Islamic Republic of Afghanistan",
  },
  { id: "ALB", id2: "AL", display: "Albania", value: "Republic of Albania" },
  {
    id: "DZA",
    id2: "DZ",
    display: "Algeria",
    value: "People's Democratic Republic of Algeria",
  },
  {
    id: "AND",
    id2: "AD",
    display: "Andorra",
    value: "Principality of Andorra",
  },
  { id: "AGO", id2: "AO", display: "Angola", value: "Republic of Angola" },
  {
    id: "ATG",
    id2: "AG",
    display: "Antigua and Barbuda",
    value: "Antigua and Barbuda",
  },
  { id: "ARG", id2: "AR", display: "Argentina", value: "Argentine Republic" },
  { id: "ARM", id2: "AM", display: "Armenia", value: "Republic of Armenia" },
  {
    id: "AUS",
    id2: "AU",
    display: "Australia",
    value: "Commonwealth of Australia",
  },
  { id: "AUT", id2: "AT", display: "Austria", value: "Republic of Austria" },
  {
    id: "AZE",
    id2: "AZ",
    display: "Azerbaijan",
    value: "Republic of Azerbaijan",
  },
  {
    id: "BHS",
    id2: "BS",
    display: "Bahamas",
    value: "Commonwealth of the Bahamas",
  },
  { id: "BHR", id2: "BH", display: "Bahrain", value: "Kingdom of Bahrain" },
  {
    id: "BGD",
    id2: "BD",
    display: "Bangladesh",
    value: "People's Republic of Bangladesh",
  },
  { id: "BRB", id2: "BB", display: "Barbados", value: "Barbados" },
  { id: "BLR", id2: "BY", display: "Belarus", value: "Republic of Belarus" },
  { id: "BEL", id2: "BE", display: "Belgium", value: "Kingdom of Belgium" },
  { id: "BLZ", id2: "BZ", display: "Belize", value: "Belize" },
  { id: "BEN", id2: "BJ", display: "Benin", value: "Republic of Benin" },
  { id: "BTN", id2: "BT", display: "Bhutan", value: "Kingdom of Bhutan" },
  {
    id: "BOL",
    id2: "BO",
    display: "Bolivia",
    value: "Plurinational State of Bolivia",
  },
  {
    id: "BIH",
    id2: "BA",
    display: "Bosnia and Herzegovina",
    value: "Bosnia and Herzegovina",
  },
  { id: "BWA", id2: "BW", display: "Botswana", value: "Republic of Botswana" },
  {
    id: "BRA",
    id2: "BR",
    display: "Brazil",
    value: "Federative Republic of Brazil",
  },
  { id: "BRN", id2: "BN", display: "Brunei", value: "Brunei Darussalam" },
  { id: "BGR", id2: "BG", display: "Bulgaria", value: "Republic of Bulgaria" },
  { id: "BFA", id2: "BF", display: "Burkina Faso", value: "Burkina Faso" },
  { id: "BDI", id2: "BI", display: "Burundi", value: "Republic of Burundi" },
  {
    id: "CPV",
    id2: "CV",
    display: "Cabo Verde",
    value: "Republic of Cabo Verde",
  },
  { id: "KHM", id2: "KH", display: "Cambodia", value: "Kingdom of Cambodia" },
  { id: "CMR", id2: "CM", display: "Cameroon", value: "Republic of Cameroon" },
  { id: "CAN", id2: "CA", display: "Canada", value: "Canada" },
  {
    id: "CAF",
    id2: "CF",
    display: "Central African Republic",
    value: "Central African Republic",
  },
  { id: "TCD", id2: "TD", display: "Chad", value: "Republic of Chad" },
  { id: "CHL", id2: "CL", display: "Chile", value: "Republic of Chile" },
  {
    id: "CHN",
    id2: "CN",
    display: "China",
    value: "People's Republic of China",
  },
  { id: "COL", id2: "CO", display: "Colombia", value: "Republic of Colombia" },
  { id: "COM", id2: "KM", display: "Comoros", value: "Union of the Comoros" },
  {
    id: "COG",
    id2: "CG",
    display: "Congo (Brazzaville)",
    value: "Republic of the Congo",
  },
  {
    id: "COD",
    id2: "CD",
    display: "Congo (Kinshasa)",
    value: "Democratic Republic of the Congo",
  },
  {
    id: "CRI",
    id2: "CR",
    display: "Costa Rica",
    value: "Republic of Costa Rica",
  },
  {
    id: "CIV",
    id2: "CI",
    display: "Côte d'Ivoire",
    value: "Republic of Côte d'Ivoire",
  },
  { id: "HRV", id2: "HR", display: "Croatia", value: "Republic of Croatia" },
  { id: "CUB", id2: "CU", display: "Cuba", value: "Republic of Cuba" },
  { id: "CYP", id2: "CY", display: "Cyprus", value: "Republic of Cyprus" },
  { id: "CZE", id2: "CZ", display: "Czechia", value: "Czech Republic" },
  { id: "DNK", id2: "DK", display: "Denmark", value: "Kingdom of Denmark" },
  { id: "DJI", id2: "DJ", display: "Djibouti", value: "Republic of Djibouti" },
  {
    id: "DMA",
    id2: "DM",
    display: "Dominica",
    value: "Commonwealth of Dominica",
  },
  {
    id: "DOM",
    id2: "DO",
    display: "Dominican Republic",
    value: "Dominican Republic",
  },
  { id: "ECU", id2: "EC", display: "Ecuador", value: "Republic of Ecuador" },
  { id: "EGY", id2: "EG", display: "Egypt", value: "Arab Republic of Egypt" },
  {
    id: "SLV",
    id2: "SV",
    display: "El Salvador",
    value: "Republic of El Salvador",
  },
  {
    id: "GNQ",
    id2: "GQ",
    display: "Equatorial Guinea",
    value: "Republic of Equatorial Guinea",
  },
  { id: "ERI", id2: "ER", display: "Eritrea", value: "State of Eritrea" },
  { id: "EST", id2: "EE", display: "Estonia", value: "Republic of Estonia" },
  { id: "SWZ", id2: "SZ", display: "Eswatini", value: "Kingdom of Eswatini" },
  {
    id: "ETH",
    id2: "ET",
    display: "Ethiopia",
    value: "Federal Democratic Republic of Ethiopia",
  },
  { id: "FJI", id2: "FJ", display: "Fiji", value: "Republic of Fiji" },
  { id: "FIN", id2: "FI", display: "Finland", value: "Republic of Finland" },
  { id: "FRA", id2: "FR", display: "France", value: "French Republic" },
  { id: "GAB", id2: "GA", display: "Gabon", value: "Gabonese Republic" },
  { id: "GMB", id2: "GM", display: "Gambia", value: "Republic of The Gambia" },
  { id: "GEO", id2: "GE", display: "Georgia", value: "Georgia" },
  {
    id: "DEU",
    id2: "DE",
    display: "Germany",
    value: "Federal Republic of Germany",
  },
  { id: "GHA", id2: "GH", display: "Ghana", value: "Republic of Ghana" },
  { id: "GRC", id2: "GR", display: "Greece", value: "Hellenic Republic" },
  { id: "GRD", id2: "GD", display: "Grenada", value: "Grenada" },
  {
    id: "GTM",
    id2: "GT",
    display: "Guatemala",
    value: "Republic of Guatemala",
  },
  { id: "GIN", id2: "GN", display: "Guinea", value: "Republic of Guinea" },
  {
    id: "GNB",
    id2: "GW",
    display: "Guinea-Bissau",
    value: "Republic of Guinea-Bissau",
  },
  {
    id: "GUY",
    id2: "GY",
    display: "Guyana",
    value: "Co-operative Republic of Guyana",
  },
  { id: "HTI", id2: "HT", display: "Haiti", value: "Republic of Haiti" },
  { id: "HND", id2: "HN", display: "Honduras", value: "Republic of Honduras" },
  { id: "HUN", id2: "HU", display: "Hungary", value: "Hungary" },
  { id: "ISL", id2: "IS", display: "Iceland", value: "Republic of Iceland" },

  {
    id: "IDN",
    id2: "ID",
    display: "Indonesia",
    value: "Republic of Indonesia",
  },
  { id: "IRN", id2: "IR", display: "Iran", value: "Islamic Republic of Iran" },
  { id: "IRQ", id2: "IQ", display: "Iraq", value: "Republic of Iraq" },
  { id: "IRL", id2: "IE", display: "Ireland", value: "Ireland" },
  { id: "ISR", id2: "IL", display: "Israel", value: "State of Israel" },
  { id: "ITA", id2: "IT", display: "Italy", value: "Italian Republic" },
  { id: "JAM", id2: "JM", display: "Jamaica", value: "Jamaica" },
  { id: "JPN", id2: "JP", display: "Japan", value: "Japan" },
  {
    id: "JOR",
    id2: "JO",
    display: "Jordan",
    value: "Hashemite Kingdom of Jordan",
  },
  {
    id: "KAZ",
    id2: "KZ",
    display: "Kazakhstan",
    value: "Republic of Kazakhstan",
  },
  { id: "KEN", id2: "KE", display: "Kenya", value: "Republic of Kenya" },
  { id: "KIR", id2: "KI", display: "Kiribati", value: "Republic of Kiribati" },
  {
    id: "PRK",
    id2: "KP",
    display: "North Korea",
    value: "Democratic People's Republic of Korea",
  },
  { id: "KOR", id2: "KR", display: "South Korea", value: "Republic of Korea" },
  { id: "KWT", id2: "KW", display: "Kuwait", value: "State of Kuwait" },
  { id: "KGZ", id2: "KG", display: "Kyrgyzstan", value: "Kyrgyz Republic" },
  {
    id: "LAO",
    id2: "LA",
    display: "Laos",
    value: "Lao People's Democratic Republic",
  },
  { id: "LVA", id2: "LV", display: "Latvia", value: "Republic of Latvia" },
  { id: "LBN", id2: "LB", display: "Lebanon", value: "Lebanese Republic" },
  { id: "LSO", id2: "LS", display: "Lesotho", value: "Kingdom of Lesotho" },
  { id: "LBR", id2: "LR", display: "Liberia", value: "Republic of Liberia" },
  { id: "LBY", id2: "LY", display: "Libya", value: "State of Libya" },
  {
    id: "LIE",
    id2: "LI",
    display: "Liechtenstein",
    value: "Principality of Liechtenstein",
  },
  {
    id: "LTU",
    id2: "LT",
    display: "Lithuania",
    value: "Republic of Lithuania",
  },
  {
    id: "LUX",
    id2: "LU",
    display: "Luxembourg",
    value: "Grand Duchy of Luxembourg",
  },
  {
    id: "MDG",
    id2: "MG",
    display: "Madagascar",
    value: "Republic of Madagascar",
  },
  { id: "MWI", id2: "MW", display: "Malawi", value: "Republic of Malawi" },
  { id: "MYS", id2: "MY", display: "Malaysia", value: "Malaysia" },
  { id: "MDV", id2: "MV", display: "Maldives", value: "Republic of Maldives" },
  { id: "MLI", id2: "ML", display: "Mali", value: "Republic of Mali" },
  { id: "MLT", id2: "MT", display: "Malta", value: "Republic of Malta" },
  {
    id: "MHL",
    id2: "MH",
    display: "Marshall Islands",
    value: "Republic of the Marshall Islands",
  },
  {
    id: "MRT",
    id2: "MR",
    display: "Mauritania",
    value: "Islamic Republic of Mauritania",
  },
  {
    id: "MUS",
    id2: "MU",
    display: "Mauritius",
    value: "Republic of Mauritius",
  },
  { id: "MEX", id2: "MX", display: "Mexico", value: "United Mexican States" },
  {
    id: "FSM",
    id2: "FM",
    display: "Micronesia",
    value: "Federated States of Micronesia",
  },
  { id: "MDA", id2: "MD", display: "Moldova", value: "Republic of Moldova" },
  { id: "MCO", id2: "MC", display: "Monaco", value: "Principality of Monaco" },
  { id: "MNG", id2: "MN", display: "Mongolia", value: "Mongolia" },
  { id: "MNE", id2: "ME", display: "Montenegro", value: "Montenegro" },
  { id: "MAR", id2: "MA", display: "Morocco", value: "Kingdom of Morocco" },
  {
    id: "MOZ",
    id2: "MZ",
    display: "Mozambique",
    value: "Republic of Mozambique",
  },
  {
    id: "MMR",
    id2: "MM",
    display: "Myanmar",
    value: "Republic of the Union of Myanmar",
  },
  { id: "NAM", id2: "NA", display: "Namibia", value: "Republic of Namibia" },
  { id: "NRU", id2: "NR", display: "Nauru", value: "Republic of Nauru" },
  {
    id: "NPL",
    id2: "NP",
    display: "Nepal",
    value: "Federal Democratic Republic of Nepal",
  },
  {
    id: "NLD",
    id2: "NL",
    display: "Netherlands",
    value: "Kingdom of the Netherlands",
  },
  { id: "NZL", id2: "NZ", display: "New Zealand", value: "New Zealand" },
  {
    id: "NIC",
    id2: "NI",
    display: "Nicaragua",
    value: "Republic of Nicaragua",
  },
  { id: "NER", id2: "NE", display: "Niger", value: "Republic of the Niger" },
  {
    id: "NGA",
    id2: "NG",
    display: "Nigeria",
    value: "Federal Republic of Nigeria",
  },
  {
    id: "MKD",
    id2: "MK",
    display: "North Macedonia",
    value: "Republic of North Macedonia",
  },
  { id: "NOR", id2: "NO", display: "Norway", value: "Kingdom of Norway" },
  { id: "OMN", id2: "OM", display: "Oman", value: "Sultanate of Oman" },
  {
    id: "PAK",
    id2: "PK",
    display: "Pakistan",
    value: "Islamic Republic of Pakistan",
  },
  { id: "PLW", id2: "PW", display: "Palau", value: "Republic of Palau" },
  { id: "PAN", id2: "PA", display: "Panama", value: "Republic of Panama" },
  {
    id: "PNG",
    id2: "PG",
    display: "Papua New Guinea",
    value: "Independent State of Papua New Guinea",
  },
  { id: "PRY", id2: "PY", display: "Paraguay", value: "Republic of Paraguay" },
  { id: "PER", id2: "PE", display: "Peru", value: "Republic of Peru" },
  {
    id: "PHL",
    id2: "PH",
    display: "Philippines",
    value: "Republic of the Philippines",
  },
  { id: "POL", id2: "PL", display: "Poland", value: "Republic of Poland" },
  { id: "PRT", id2: "PT", display: "Portugal", value: "Portuguese Republic" },
  { id: "QAT", id2: "QA", display: "Qatar", value: "State of Qatar" },
  { id: "ROU", id2: "RO", display: "Romania", value: "Romania" },
  { id: "RUS", id2: "RU", display: "Russia", value: "Russian Federation" },
  { id: "RWA", id2: "RW", display: "Rwanda", value: "Republic of Rwanda" },
  {
    id: "KNA",
    id2: "KN",
    display: "Saint Kitts and Nevis",
    value: "Federation of Saint Christopher and Nevis",
  },
  { id: "LCA", id2: "LC", display: "Saint Lucia", value: "Saint Lucia" },
  {
    id: "VCT",
    id2: "VC",
    display: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  {
    id: "WSM",
    id2: "WS",
    display: "Samoa",
    value: "Independent State of Samoa",
  },
  {
    id: "SMR",
    id2: "SM",
    display: "San Marino",
    value: "Republic of San Marino",
  },
  {
    id: "STP",
    id2: "ST",
    display: "Sao Tome and Principe",
    value: "Democratic Republic of Sao Tome and Principe",
  },
  {
    id: "SAU",
    id2: "SA",
    display: "Saudi Arabia",
    value: "Kingdom of Saudi Arabia",
  },
  { id: "SEN", id2: "SN", display: "Senegal", value: "Republic of Senegal" },
  { id: "SRB", id2: "RS", display: "Serbia", value: "Republic of Serbia" },
  {
    id: "SYC",
    id2: "SC",
    display: "Seychelles",
    value: "Republic of Seychelles",
  },
  {
    id: "SLE",
    id2: "SL",
    display: "Sierra Leone",
    value: "Republic of Sierra Leone",
  },
  {
    id: "SGP",
    id2: "SG",
    display: "Singapore",
    value: "Republic of Singapore",
  },
  { id: "SVK", id2: "SK", display: "Slovakia", value: "Slovak Republic" },
  { id: "SVN", id2: "SI", display: "Slovenia", value: "Republic of Slovenia" },
  {
    id: "SLB",
    id2: "SB",
    display: "Solomon Islands",
    value: "Solomon Islands",
  },
  {
    id: "SOM",
    id2: "SO",
    display: "Somalia",
    value: "Federal Republic of Somalia",
  },
  {
    id: "ZAF",
    id2: "ZA",
    display: "South Africa",
    value: "Republic of South Africa",
  },
  {
    id: "SSD",
    id2: "SS",
    display: "South Sudan",
    value: "Republic of South Sudan",
  },
  { id: "ESP", id2: "ES", display: "Spain", value: "Kingdom of Spain" },
  {
    id: "LKA",
    id2: "LK",
    display: "Sri Lanka",
    value: "Democratic Socialist Republic of Sri Lanka",
  },
  { id: "SDN", id2: "SD", display: "Sudan", value: "Republic of the Sudan" },
  { id: "SUR", id2: "SR", display: "Suriname", value: "Republic of Suriname" },
  { id: "SWE", id2: "SE", display: "Sweden", value: "Kingdom of Sweden" },
  {
    id: "CHE",
    id2: "CH",
    display: "Switzerland",
    value: "Swiss Confederation",
  },
  { id: "SYR", id2: "SY", display: "Syria", value: "Syrian Arab Republic" },
  {
    id: "TWN",
    id2: "TW",
    display: "Taiwan",
    value: "Republic of China (Taiwan)",
  },
  {
    id: "TJK",
    id2: "TJ",
    display: "Tajikistan",
    value: "Republic of Tajikistan",
  },
  {
    id: "TZA",
    id2: "TZ",
    display: "Tanzania",
    value: "United Republic of Tanzania",
  },
  { id: "THA", id2: "TH", display: "Thailand", value: "Kingdom of Thailand" },
  {
    id: "TLS",
    id2: "TL",
    display: "Timor-Leste",
    value: "Democratic Republic of Timor-Leste",
  },
  { id: "TGO", id2: "TG", display: "Togo", value: "Togolese Republic" },
  { id: "TON", id2: "TO", display: "Tonga", value: "Kingdom of Tonga" },
  {
    id: "TTO",
    id2: "TT",
    display: "Trinidad and Tobago",
    value: "Republic of Trinidad and Tobago",
  },
  { id: "TUN", id2: "TN", display: "Tunisia", value: "Tunisian Republic" },
  { id: "TUR", id2: "TR", display: "Turkey", value: "Republic of Turkey" },
  { id: "TKM", id2: "TM", display: "Turkmenistan", value: "Turkmenistan" },
  { id: "TUV", id2: "TV", display: "Tuvalu", value: "Tuvalu" },
  { id: "UGA", id2: "UG", display: "Uganda", value: "Republic of Uganda" },
  { id: "UKR", id2: "UA", display: "Ukraine", value: "Ukraine" },
  {
    id: "ARE",
    id2: "AE",
    display: "United Arab Emirates",
    value: "United Arab Emirates",
  },
  {
    id: "GBR",
    id2: "GB",
    display: "United Kingdom",
    value: "United Kingdom of Great Britain and Northern Ireland",
  },
  {
    id: "USA",
    id2: "US",
    display: "United States",
    value: "United States of America",
  },
  {
    id: "URY",
    id2: "UY",
    display: "Uruguay",
    value: "Oriental Republic of Uruguay",
  },
  {
    id: "UZB",
    id2: "UZ",
    display: "Uzbekistan",
    value: "Republic of Uzbekistan",
  },
  { id: "VUT", id2: "VU", display: "Vanuatu", value: "Republic of Vanuatu" },
  {
    id: "VEN",
    id2: "VE",
    display: "Venezuela",
    value: "Bolivarian Republic of Venezuela",
  },
  {
    id: "VNM",
    id2: "VN",
    display: "Vietnam",
    value: "Socialist Republic of Vietnam",
  },
  { id: "YEM", id2: "YE", display: "Yemen", value: "Republic of Yemen" },
  { id: "ZMB", id2: "ZM", display: "Zambia", value: "Republic of Zambia" },
  { id: "ZWE", id2: "ZW", display: "Zimbabwe", value: "Republic of Zimbabwe" },
];
